/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multilib.kotlin-application-conventions")
}

application {
    mainClass.set("multilib.client.AppKt")
}

dependencies {
    api(project(":lib"))
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.8")
}
