/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multilib.kotlin-application-conventions")
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1")
    implementation("io.jsonwebtoken:jjwt-api:0.11.5")
    implementation("io.jsonwebtoken:jjwt-impl:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.5")
    runtimeOnly("org.postgresql:postgresql:42.5.2")
    implementation("org.apache.commons:commons-text")
    implementation(project(":lib"))
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.8")
}

application {
    // Define the main class for the application.
    mainClass.set("multilib.server.AppKt")
}
