/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package multilib.server

import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import multilib.app.CommandManager
import multilib.app.Operator
import multilib.server.city.CityCollection
import multilib.app.commands.*
import multilib.app.senders.USender
import multilib.server.commands.*
import multilib.server.commands.Long
import multilib.server.commands.users.Authorization
import multilib.server.commands.users.SignUp
import multilib.server.server.UpdServer
import multilib.server.server.actors.CollectionActor
import multilib.server.server.actors.DataBaseActor


val collection = CityCollection()
val operator = Operator()
val commandManager = CommandManager()
val uSender = USender()
val collectionActor = CollectionActor()
val databaseActor = DataBaseActor()


fun main() : Unit = runBlocking{
    commandManager.register(
        Add(), Clear(), ExecuteScript(), Exit(), FilterContainsName(), Help(), Info(),
        PrintAscending(), RemoveAllByMetersAboveSeaLevel(), RemoveAt(), RemoveById(), RemoveLower(), Show(), Sort(), UpdateById(), Long(),
        Authorization(), SignUp()
    )
    coroutineScope {
        launch {
            UpdServer().run().join()
        }
    }
}

