/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package multilib.app

import multilib.app.city.CityCollection
import multilib.app.commands.tools.Validator
import multilib.app.senders.USender
import multilib.app.commands.*
import multilib.app.server.UpdServer
import multilib.list.Serialization


val collection = CityCollection()
val operator = Operator()
val commandManager = CommandManager()
val uSender = USender()
val validator = Validator()


fun main(){
    commandManager.register(Add(), Clear(), ExecuteScript(), Exit(), FilterContainsName(), Help(), Info(),
        PrintAscending(), RemoveAllByMetersAboveSeaLevel(), RemoveAt(), RemoveById(), RemoveLower(), Show(), Sort(), UpdateById())

    UpdServer().run()

}
